### ISSUE TITLE
Device Failure: Relationship between attributes needed

### ISSUE THREAD

**Issue by godelstheory** [mozilla-outreachy-datascience/outreachy-datascience#1]
The relationship between the attributes is poorly understood. A better understanding is needed in this regard for the data we are collecting.
* What is the correlation between the attributes?
* How do the scales differ or are similar between attributes?

**Comment by AmaniAbbas** [comment]
I am working on this issue

**Comment by Sando1** [comment]
@AmaniAbbas I will work on this issue with you. All other issues are take up. Let us divide and conquer.

**Comment by teonbrooks** [comment]
dear prospective(s), the deadline for completion of your issue is the end of Thursday, Oct 25 your local time. for full message, please read [this comment](https://gitter.im/mozilla-outreachy-datascience/outreachy-datascience?at=5bd1a60482893a2f3b394f2f) on Gitter.

**Comment by sharonteles** [comment]
Hello, I wolud like to submit an answer to these questions. Thank you.

**Comment by teonbrooks** [comment]
dear prospective(s), we announced in Gitter that the deadline for completion has been extended to the end of Sunday, Oct 28 your local time. for full message, please read this [comment](https://gitter.im/mozilla-outreachy-datascience/outreachy-datascience?at=5bd2f68164cfc273f92a8146).

**Comment by sharonteles** [comment]
Hello @teonbrooks I just finished my response. Where can I find the option to submit my file in the proposal page? I'm not used to github... Thank you.

**Comment by sharonteles** [comment]
Hello @teonbrooks, is the file I sent to you public?

**Comment by sharonteles** [comment]
Good night @teonbrooks should I record my contribution and register my final application on the Outreachy website? It says it's due to oct 30... Are you going to review here first or should I send it now? Thank you!

**Comment by teonbrooks** [comment]
@sharonteles yes, i see your pr. we will be reviewing them this week so thanks for submitting your pr
