### ISSUE TITLE
School-YRBS: Integrity of data

### ISSUE THREAD

**Issue by godelstheory** [mozilla-outreachy-datascience/outreachy-datascience#10]
A big concern is the overall integrity of the school dataset, which needs to be addressed through investigation.

* Is there missing data?
* Is the data consistent?
* Are there bugs in the data?

**Comment by skandamurthy** [comment]
@godelstheory I would like to start working on this issue

**Comment by teonbrooks** [comment]
dear prospective(s), the deadline for completion of your issue is the end of Thursday, Oct 25 your local time. for full message, please read [this comment](https://gitter.im/mozilla-outreachy-datascience/outreachy-datascience?at=5bd1a60482893a2f3b394f2f) on Gitter.

**Comment by teonbrooks** [comment]
dear prospective(s), we announced in Gitter that the deadline for completion has been extended to the end of Sunday, Oct 28 your local time. for full message, please read this [comment](https://gitter.im/mozilla-outreachy-datascience/outreachy-datascience?at=5bd2f68164cfc273f92a8146).

**Comment by skandamurthy** [comment]
Sorry for the mess @godelstheory and @teonbrooks. I had some issues with my laptop and now after at the last minute, i couldn't get a seperate pull-request so hastely i have referred to my 1st issue where both answers are available. It is ok for you to select any one of them randomly and evaluate it. Both answers are equally-correct according to me.

**Comment by teonbrooks** [comment]
@skandamurthy got it. thanks for submitting your pr, we will be evaluating the prs this week
