### ISSUE TITLE
School-YRBS: Friends

### ISSUE THREAD

**Issue by godelstheory** [mozilla-outreachy-datascience/outreachy-datascience#11]
The administration wants to better understand the social dynamic of the high school. The dataset contains a relevant column called `friends`, which is the number of friends of the student. 

* What is the distribution of the number of friends?
* What are the gender breakdown of friends?
* What is the breakdown by race?

**Comment by kristhayer94** [comment]
I will start working on this issue.

**Comment by MadinaB** [comment]
I will be working on this one, too. Sorry, like every other issue is also busy and people even started to share them..

**Comment by jyox007** [comment]
I am working on it

**Comment by jyoti-u** [comment]
@godelstheory @teonbrooks I am also working on this issue.

**Comment by teonbrooks** [comment]
dear prospective(s), the deadline for completion of your issue is the end of Thursday, Oct 25 your local time. for full message, please read [this comment](https://gitter.im/mozilla-outreachy-datascience/outreachy-datascience?at=5bd1a60482893a2f3b394f2f) on Gitter.

**Comment by shruthi0898** [comment]
Hello @teonbrooks 
I just got my eligibility checked and would like to contribute to some issues. Am I still allowed to contribute? Please let me know.

**Comment by teonbrooks** [comment]
dear prospective(s), we announced in Gitter that the deadline for completion has been extended to the end of Sunday, Oct 28 your local time. for full message, please read this [comment](https://gitter.im/mozilla-outreachy-datascience/outreachy-datascience?at=5bd2f68164cfc273f92a8146).

**Comment by teonbrooks** [comment]
hi @shruthi0898, feel free to contribute to one issue and submit your response as a PR by the end of your local day.

**Comment by JulietaCaceres** [comment]
Hi! :)
I was working on this!
Sorry for the delay in commenting but I miss this detail.

**Comment by teonbrooks** [comment]
@JulietaCaceres as long as your pr is in, it is fine.
