### ISSUE TITLE
School-YRBS: Parents column

### ISSUE THREAD

**Issue by godelstheory** [mozilla-outreachy-datascience/outreachy-datascience#12]
The current dataset stores parent information in the `parents` field. One value is `my mother and my father`. It is desirable to break out this information into single caregivers. e.g., `my mother and my father` becomes `mother` and `father`, whereas `my mother only` is just mother. 

* What is the distribution of each single caregiver type? e.g., What is the distribution of `mother` caregiver?

**Comment by mridubhatnagar** [comment]
@godelstheory @teonbrooks I am working on this issue

**Comment by brunapinos** [comment]
@godelstheory @teonbrooks I am working on this issue too :)

**Comment by jyoti-u** [comment]
@godelstheory @teonbrooks I am also working on this issue

**Comment by teonbrooks** [comment]
dear prospective(s), the deadline for completion of your issue is the end of Thursday, Oct 25 your local time. for full message, please read [this comment](https://gitter.im/mozilla-outreachy-datascience/outreachy-datascience?at=5bd1a60482893a2f3b394f2f) on Gitter.

**Comment by skandamurthy** [comment]
@godelstheory @teonbrooks  I am working on this too.

**Comment by teonbrooks** [comment]
dear prospective(s), we announced in Gitter that the deadline for completion has been extended to the end of Sunday, Oct 28 your local time. for full message, please read this [comment](https://gitter.im/mozilla-outreachy-datascience/outreachy-datascience?at=5bd2f68164cfc273f92a8146).

**Comment by shruthi0898** [comment]
Working on this! :)

**Comment by skandamurthy** [comment]
> @godelstheory @teonbrooks I am working on this too.

#10 12th issue answer

**Comment by milena-rosa** [comment]
Hello, @teonbrooks,
I am working on this issue as well!
