### ISSUE TITLE
Device Failure: Reduce Number of Telemetry Attributes

### ISSUE THREAD

**Issue by godelstheory** [mozilla-outreachy-datascience/outreachy-datascience#2]
The current telemetry payload is too large. We need a good representation that approximates the dataset, with a reduced number of columns. 
* What are some methods for reducing the size of the dataset?
* What is the trade-off between dataset size and fidelity to original dataset

**Comment by rabyatouyimga** [comment]
@godelstheory I shall work on this issue.

**Comment by Sando1** [comment]
@teonbrooks  Would like to work on this as well.

**Comment by jyoti-u** [comment]
@teonbrooks @godelstheory I have solved this issue but I am facing some sort of issues in sending the pull request on GitHub. So I have sent you my code, will try to upload code on GitHub as soon as possible.

**Comment by teonbrooks** [comment]
dear prospective(s), the deadline for completion of your issue is the end of Thursday, Oct 25 your local time. for full message, please read [this comment](https://gitter.im/mozilla-outreachy-datascience/outreachy-datascience?at=5bd1a60482893a2f3b394f2f) on Gitter.

**Comment by teonbrooks** [comment]
@jyox007 sorry for the difficulties with GH. I believe they have resolved their outstanding issues and things should be working again.

**Comment by jyoti-u** [comment]
I have solved the issue, but I am not able to add the solution separately. So I have made a reference for this solution., using which one can see my solution.

**Comment by teonbrooks** [comment]
dear prospective(s), we announced in Gitter that the deadline for completion has been extended to the end of Sunday, Oct 28 your local time. for full message, please read this [comment](https://gitter.im/mozilla-outreachy-datascience/outreachy-datascience?at=5bd2f68164cfc273f92a8146).
