### ISSUE TITLE
Device Failure: Attributes and Failure Mode

### ISSUE THREAD

**Issue by godelstheory** [mozilla-outreachy-datascience/outreachy-datascience#3]
A better understanding is needed on how the attributes relate to device failure.
* How do the attributes relate to device failure?
* Is there a single attribute, or a combination of the attributes, that follows device failure?

**Comment by ghost** [comment]
Working on it :)

**Comment by goose-life** [comment]
I'd like to give this one a go too, given that they're all taken I hope this is alright?

**Comment by teonbrooks** [comment]
@goose-life it's ok if you are working on the same problem. sorry for the delay in response

**Comment by teonbrooks** [comment]
dear prospective(s), the deadline for completion of your issue is the end of Thursday, Oct 25 your local. for full message, please read [this comment](https://gitter.im/mozilla-outreachy-datascience/outreachy-datascience?at=5bd1a60482893a2f3b394f2f) on Gitter.

**Comment by teonbrooks** [comment]
dear prospective(s), we announced in Gitter that the deadline for completion has been extended to the end of Sunday, Oct 28 your local time. for full message, please read this [comment](https://gitter.im/mozilla-outreachy-datascience/outreachy-datascience?at=5bd2f68164cfc273f92a8146).
