### ISSUE TITLE
Device Failure: Chacteristics of Failed Devices

### ISSUE THREAD

**Issue by godelstheory** [mozilla-outreachy-datascience/outreachy-datascience#4]
A better understanding is needed regarding the behavior of failed devices.
* How many devices failed?
* How often do they fail?
* When do they fail?

**Comment by luciakasman** [comment]
Hi, I'm going to work on this issue.

**Comment by teonbrooks** [comment]
dear prospective(s), the deadline for completion of your issue is the end of Thursday, Oct 25 your local time. for full message, please read [this comment](https://gitter.im/mozilla-outreachy-datascience/outreachy-datascience?at=5bd1a60482893a2f3b394f2f) on Gitter.

**Comment by Wyrd00** [comment]
Hello, I would like to work on this issue!

**Comment by teonbrooks** [comment]
dear prospective(s), we announced in Gitter that the deadline for completion has been extended to the end of Sunday, Oct 28 your local time. for full message, please read this [comment](https://gitter.im/mozilla-outreachy-datascience/outreachy-datascience?at=5bd2f68164cfc273f92a8146).
