### ISSUE TITLE
Device Failure: Integrity of Telemetry Data

### ISSUE THREAD

**Issue by godelstheory** [mozilla-outreachy-datascience/outreachy-datascience#5]
A big concern is the overall integrity of the telemetry data, which needs to be addressed through investigation.
* Is there missing data?
* Is the data consistent?
* Are there bugs in the data?

**Comment by navgurukul-shivani18** [comment]
I am working on this issue

**Comment by teonbrooks** [comment]
dear prospective(s), the deadline for completion of your issue is the end of Thursday, Oct 25 your local time. for full message, please read [this comment](https://gitter.im/mozilla-outreachy-datascience/outreachy-datascience?at=5bd1a60482893a2f3b394f2f) on Gitter.

**Comment by teonbrooks** [comment]
dear prospective(s), we announced in Gitter that the deadline for completion has been extended to the end of Sunday, Oct 28 your local time. for full message, please read this [comment](https://gitter.im/mozilla-outreachy-datascience/outreachy-datascience?at=5bd2f68164cfc273f92a8146).
