### ISSUE TITLE
Device Failue: Modeling Dataset - Feature Generation

### ISSUE THREAD

**Issue by godelstheory** [mozilla-outreachy-datascience/outreachy-datascience#6]
The desire is to try to utilize the telemetry attributes to predict device failure in the field. This requires generating a feature set for use in modeling.
* What are good features for modeling device failure?
* How would you choose the best features?

**Comment by badil96** [comment]
Hi, I want to work on this one.

**Comment by Sando1** [comment]
@badil96 considering how all issues have been taken be someone, I'd also like to work on this one. Can we divide up the work please?

**Comment by Sando1** [comment]
@teonbrooks I would like to work on this as well

**Comment by badil96** [comment]
I think the mentors said that each issue should be worked on by only one prospect. So I think you should ask them about that first.

________________________________

**Comment by teonbrooks** [comment]
hi @Sando1,  @badil96. thanks for the interests. yes, we did mention one per issue before but we have realized that there were was interest than issues we generated. we have relaxed the policy on one person per issue so both of you, feel free to work on this issue. sorry for the confusion

**Comment by teonbrooks** [comment]
dear prospective(s), the deadline for completion of your issue is the end of Thursday, Oct 25 your local time. for full message, please read [this comment](https://gitter.im/mozilla-outreachy-datascience/outreachy-datascience?at=5bd1a60482893a2f3b394f2f) on Gitter.

**Comment by badil96** [comment]
Hi,
I am having a problem submitting the PR but I am trying to figure it out but I am going to miss the deadline a little. Sorry about that.
Baraah
________________________________

**Comment by teonbrooks** [comment]
dear prospective(s), we announced in Gitter that the deadline for completion has been extended to the end of Sunday, Oct 28 your local time. for full message, please read this [comment](https://gitter.im/mozilla-outreachy-datascience/outreachy-datascience?at=5bd2f68164cfc273f92a8146).

**Comment by teonbrooks** [comment]
@badil96 we updated the deadline so as long as it is in by the end of your local day, it is fine
