### ISSUE TITLE
Device Failure: Seasonality Effects

### ISSUE THREAD

**Issue by godelstheory** [mozilla-outreachy-datascience/outreachy-datascience#7]
It is important to determine if there are seasonality effects regarding the telemetry data. 
* What seasonality effects are observed in the data?
* Is there seasonality influences in device failure?

**Comment by ghost** [comment]
I would like to work on it.

**Comment by RutujaJadhav** [comment]
Would like to work on it.

**Comment by teonbrooks** [comment]
dear prospective(s), the deadline for completion of your issue is the end of Thursday, Oct 25 your local time. for full message, please read [this comment](https://gitter.im/mozilla-outreachy-datascience/outreachy-datascience?at=5bd1a60482893a2f3b394f2f) on Gitter.

**Comment by teonbrooks** [comment]
dear prospective(s), we announced in Gitter that the deadline for completion has been extended to the end of Sunday, Oct 28 your local time. for full message, please read this [comment](https://gitter.im/mozilla-outreachy-datascience/outreachy-datascience?at=5bd2f68164cfc273f92a8146).
